# Generated by Django 5.2.1 on 2025-06-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha_actualizacion']},
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('CARRITO', 'Carrito activo'), ('PENDIENTE', 'Pendiente de validación'), ('CONFIRMADA', 'Pago confirmado'), ('RECHAZADA', 'Pago rechazado')], default='CARRITO', max_length=12),
        ),
    ]
